//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcumentPlan
    {
        public int SerialNo { get; set; }
        public Nullable<int> PId { get; set; }
        public System.DateTime Sheduledate { get; set; }
        public string Remarks { get; set; }
        public decimal Qty { get; set; }
        public decimal EstimatedUnitPrice { get; set; }
        public decimal EstimatetedTotalPrice { get; set; }
        public string CurrentStatusofProcumentPreparednessActivities { get; set; }
        public string LevelOfAuthority { get; set; }
        public string IdentificationCode { get; set; }
        public Nullable<int> Cid { get; set; }
        public string ProcumentMethod { get; set; }
        public string SourceOfFunding { get; set; }
        public string PriorityStatus { get; set; }
        public string ItemDescription { get; set; }
    }
}
