//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestItem
    {
        public int Itemid { get; set; }
        public string Itemdescription { get; set; }
        public string ItemSpecification { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> EstimatePrice { get; set; }
        public string ItemPhoto { get; set; }
        public Nullable<int> reqcid { get; set; }
        public Nullable<int> reqid { get; set; }
    }
}
