//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuatationLetter
    {
        public string QutationNo { get; set; }
        public string SendAddress { get; set; }
        public System.DateTime SendDate { get; set; }
        public System.DateTime ClosingDate { get; set; }
        public string CompanyRegistrationNo { get; set; }
        public string CompanyName { get; set; }
        public int Paperid { get; set; }
    }
}
