//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqestPaperAdditem
    {
        public int Cid { get; set; }
        public int Id { get; set; }
        public int PaperId { get; set; }
        public string Item { get; set; }
        public decimal Qty { get; set; }
        public int Rid { get; set; }
    }
}
