//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyRegistraion
    {
        public int PaperId { get; set; }
        public string CompanyRegistrationNo { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string CompanyName { get; set; }
        public int Id { get; set; }
        public string Address { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    }
}
