//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperAdd
    {
        public string Heading { get; set; }
        public int Cid { get; set; }
        public int Paperid { get; set; }
        public string TenderName { get; set; }
        public string TenderNo { get; set; }
        public decimal PaymentStatus { get; set; }
        public System.DateTime ShouldResponseDate { get; set; }
        public System.DateTime MadeDate { get; set; }
        public System.DateTime RegistrationEndDate { get; set; }
        public System.DateTime RegistrationStartDate { get; set; }
        public string RegistrationStartTime { get; set; }
        public string RegistrationEndTime { get; set; }
    }
}
